### ISSUE TITLE
[Feature Request] Height offset for SoftLanding.

### ISSUE THREAD

**Issue by jdmj** [Kerbas-ad-astra/XTLandertron#4]
A tweakable which would allow to kill velocity at certain surface altitude/impact distance.
Use case: cool airbag landing, with landertrons stopping lander at, say, 20 meters high and then propulsion module with landertrons decouples and shoots away on separatrons and lander itself inflates airbags and falls down.
My attempt at this was kinda foobar: landertrons refuse to stop firing when they should, and I fail to understand why this happens. All I do is patch the impact distance calculation to make handler think that vessel is closer to surface than it really is.

Diff for reference:

```
+++ b/Landertron/source/Landertron.cs
@@ -52,6 +52,9 @@ namespace Landertron
         [KSPField(isPersistant = false)]
         public string animationName;

+        [KSPField(isPersistant = true, guiActiveEditor = false, guiName = "Offset"), UI_FloatRange(minValue = 0f, maxValue = 100f, stepIncrement = 5f)]
+        public float slOffset = 0f;
+
         // KSPField doesn't like enums or properties so this will be persisted in OnLoad/OnSave.
         Mode _mode = Mode.SoftLanding;
         public Mode mode
@@ -146,12 +149,14 @@ namespace Landertron
             {
                 case Mode.SoftLanding:
                     mode = Mode.ShortLanding;
+                    Fields ["slOffset"].guiActiveEditor = false;
                     break;
                 case Mode.ShortLanding:
                     mode = Mode.StayPut;
                     break;
                 case Mode.StayPut:
                     mode = Mode.SoftLanding;
+                    Fields ["slOffset"].guiActiveEditor = true;
                     break;
             }
             forAllSym();

--- a/Landertron/source/ModeHandlers/SoftLandingHandler.cs
+++ b/Landertron/source/ModeHandlers/SoftLandingHandler.cs
@@ -122,7 +122,7 @@ namespace Landertron
                 }
             }

-            return distanceToImpact - maxExtent;
+            return distanceToImpact - maxExtent - armedLandertrons.Find(x => x.mode == Landertron.Mode.SoftLanding).slOffset;
         }
     }
 }
```

**Comment by jdmj** [comment]
Ah, I'm stupid. Got it. the last part should look like this:

```
            double distOffset = 0;
            if (armedLandertrons.Count > 0) {
                distOffset = armedLandertrons.Find (x => x.mode == Landertron.Mode.SoftLanding).slOffset;
            } else if (firingLandertrons.Count > 0) {
                distOffset = firingLandertrons.Find (x => x.mode == Landertron.Mode.SoftLanding).slOffset;
            }
            return distanceToImpact - maxExtent - distOffset;
```

Of course, this code may provide random result if there are several symmetry groups of landertrons with different offsets because it just uses first one it finds, but it's good enough for me. =)

**Comment by Kerbas-ad-astra** [comment]
I'm not really in a position to set aside time for KSP modding right now, so this is going to have to wait.  Also, "random results" depending on the part setup is not desirable.  Landertrons are controlled by some common (i.e. vessel-wide) controller classes now, so I'd a be more willing to accept a pull request if you could find a way to let the part modules synchronize.
