### ISSUE TITLE
Always out of electricity

### ISSUE THREAD

**Issue by dosluke** [Kerbas-ad-astra/XTLandertron#8]
when i try to activate landertrons it says they have run out of electricity, even if its a few seconds after launch. my vessel has 250 electricity. tried two of the parts.

**Comment by dosluke** [comment]
https://www.youtube.com/watch?v=GZtdVnMdoX8

**Comment by Kerbas-ad-astra** [comment]
I'm seeing that in testing now...I didn't before, but it's possible I changed something after the last good test that caused a regression (might have been https://github.com/Kerbas-ad-astra/XTLandertron/commit/36505d03711fd7f14480a7fbe015982c0b2318ac#diff-0eef0f9625e203876df447717bd6347cL48).

**Comment by dosluke** [comment]
do you know when it will be updated?
